spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/raceratingdb
    username: postgres
    password: postgres
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  oauth2:
    redirectUri: http://localhost:4200/oauth2/redirect
  cors:
    allowed-origins: http://localhost:4200

