spring:
  application:
    name: rate-rating-api
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATABASE_PRIVATE_URL:jdbc:postgresql://localhost:5432/raceratingdb}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
aws:
  s3:
    bucket: race-rating
  region: eu-central-1

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  oauth2:
#    redirectUri: http://localhost:3000/oauth2/redirect
    redirectUri: http://localhost:4200/oauth2/redirect
  cors:
#    allowed-origins: http://localhost:3000
    allowed-origins: http://localhost:4200


logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
