spring:
  application:
    name: rate-rating-api
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

aws:
  s3:
    bucket: race-rating
  region: eu-central-1
  ses:
    senderEmail: no-reply@racerating.bg

app:
  public-domain: ${UI_PUBLIC_DOMAIN:localhost:4200}
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10

security:
  jwt:
    refresh-token:
      expiration-time: 7d

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG

raceRating:
  logoProcessor:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health