version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: raceratingdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: "pg_isready -U postgres"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080

  race-rating-api:
    image: ivan4oto/race-rating-api
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/raceratingdb
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - postgres

  race-rating-ui:
    image: ivan4oto/race-rating-ui
    ports:
      - "80:80"
    depends_on:
      - race-rating-api