# Stage 1: Build the application
FROM maven:3.8.4-openjdk-17-slim as build

# Set the working directory in the Docker container
WORKDIR /app

# Copy the pom.xml file to fetch dependencies
COPY race-rating-api/pom.xml /app/

# Fetch the dependencies
RUN mvn dependency:go-offline

# Copy the project source
COPY race-rating-api/src /app/src

# Build the project
RUN mvn package -DskipTests

# Stage 2: Run the application
FROM openjdk:17-jdk-slim

# Install fonts and fontconfig
RUN apt-get update && apt-get install -y --no-install-recommends \
    fontconfig \
    libfreetype6 \
    fonts-dejavu-core \
 && rm -rf /var/lib/apt/lists/*

# Copy the built application from the previous stage
COPY --from=build /app/target/*.jar app.jar

# Expose the port the app runs on
EXPOSE 8080

# Setting the Spring profile to PROD
ENV SPRING_PROFILES_ACTIVE=prod

# Command to run the application
CMD ["java", "-jar", "app.jar"]
