export interface RaceListModel {
  id: number,
  name: string,
  description: string,
  elevation: number,
  distance: number,
  latitude: number,
  longitude: number,
  terrain: string,
  rating: number,
  logoUrl: string,
  websiteUrl: string,
  averageRating: number,
  eventDate: Date,
}
