export interface RaceListModel {
  id: number,
  name: string,
  description: string,
  averageRating: number,
  averageTraceScore: number,
  averageVibeScore: number,
  averageOrganizationScore: number,
  averageLocationScore: number,
  averageValueScore: number,
  ratingsCount: number,
  latitude: number,
  longitude: number,
  rating: number,
  logoUrl: string,
  websiteUrl: string,
  eventDate: Date,
}
